// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

// .env sebagai default. Saat NODE_ENV=test (mis. `npm run test:db:push`),
// .env.test menimpanya agar perintah DB menargetkan database uji, bukan produksi.
dotenv.config();
if (process.env.NODE_ENV === "test") {
  dotenv.config({ path: ".env.test", override: true });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
